### ISSUE TITLE
Monkey Patch Support MacOS M1 (darwin/arm64)

### ISSUE THREAD

**Issue by trungdlp-wolffun** [jxskiss/gopkg#45]

**Comment by jxskiss** [comment]
@trungdlp-wolffun Hi, code in branch `monkey_darwin_arm64` supports arm64, but I don't have a m1 machine to test it, would you like to help check it?

You can do these steps to verify it works:
1) checkout the code, then run `make test_monkey`
2) write some code and testing it using the monkey package

If you encounter any problem, please report it here.

**Comment by jxskiss** [comment]
I have merged the changes to master and tagged new release, you may try the latest version.
