### ISSUE TITLE
Modify the import of github.com/bytedance/sonic/encoder in github.com/jxskiss/gopkg/v2/perf/json to github.com/bytedance/sonic

### ISSUE THREAD

**Issue by BruceLoveDecimal** [jxskiss/gopkg#49]
Hello, I found ur repo in github.com/jxskiss/gopkg/v2/perf/json using github.com/bytedance/sonic/encoder.But when it was ran on the M1 Macbook, it will go wrong with the error, imports github.com/bytedance/sonic/internal/native: build constraints exclude all Go files in /Users/bytedance/go/pkg/mod/github.com/bytedance/sonic@v1.8.5/internal/native. So in order to support M1, according to the doc of bytedance/sonic, github.com/bytedance/sonic/decoder can be modified to github.com/bytedance/sonic. If there are any further questions, please reply to me as soon as possible.

**Comment by jxskiss** [comment]
Thanks for your feedback! The build failure has been fixed in newer release, you may try the latest version. If it still fails please let me know.
Also the default underlying library has been changed to jsonitor since sonic has some silence bug which generates incorrect result.
